version: "3"

services:
  database:
    build: ./database
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./data:/app/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/code:/var/opt/gis
      - ./data:/app/code/data

  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/var/opt/gis/src

volumes:
  database-data:
